import React,{useState,useEffect,useRef} from 'react';
import{createRoot}from'react-dom/client';
import{Copy,Volume2,VolumeX,ArrowUpRight}from'lucide-react';
import'./style.css';

const CA='0x0000000000000000000000000000000000000069';
const links=[['WELCOME','#welcome'],['HOW 2 ACQUIRE','#buy'],['THE LORE','#lore'],['TOKENOMICS','#tokenomics'],['CHART GO UP','#chart'],['CURSED FILES','#memes']];
const communityMemes=[
 ['/assets/community/slam-dunk.jpeg','DIAMOND-HANDS SLAM DUNK'],
 ['/assets/community/poker.jpeg','HIGH-STAKES DUMB-MONEY POKER'],
 ['/assets/community/diamond.jpeg','THE DIAMOND CHAIN INCIDENT'],
 ['/assets/community/fourth-wall.jpeg','PUMP THE DOGES / DUMP THE STOCKS'],
 ['/assets/community/fox-cash.jpeg','FOX ARCHER CASH-FAN CEREMONY'],
 ['/assets/community/mascot.jpeg','THE OFFICIAL UNOFFICIAL MASCOT'],
 ['/assets/community/diamond-chain.jpeg','DEEP-FRIED DIAMOND CHAIN FOX']
];

function App(){
 const[truth,setTruth]=useState(false),[sound,setSound]=useState(false),[copied,setCopied]=useState(false),[price,setPrice]=useState(0.0000069),[popups,setPopups]=useState([1,2]),[chat,setChat]=useState(0),[depth,setDepth]=useState(12); const abyssRef=useRef(null);
 useEffect(()=>{const t=setInterval(()=>setPrice(p=>Math.max(.0000001,p*(1+(Math.random()-.42)*.045))),900);return()=>clearInterval(t)},[]);
 useEffect(()=>{let last=0;const move=e=>{if(Date.now()-last<70)return;last=Date.now();const g=document.createElement('img');g.src='/assets/robin-neon-smiley.png';g.className='cursor-gem';g.style.left=e.clientX+'px';g.style.top=e.clientY+'px';document.body.appendChild(g);setTimeout(()=>g.remove(),850)};window.addEventListener('mousemove',move);return()=>window.removeEventListener('mousemove',move)},[]);
 useEffect(()=>{const t=setInterval(()=>setChat(c=>(c+1)%5),2400);return()=>clearInterval(t)},[]);
 useEffect(()=>{const t=setInterval(()=>{const c=document.createElement('img');c.src='/assets/robin-neon-smiley.png';c.className='raincoin';c.style.left=Math.random()*96+'vw';c.style.width=(22+Math.random()*38)+'px';document.body.appendChild(c);setTimeout(()=>c.remove(),4200)},480);return()=>clearInterval(t)},[]);
 useEffect(()=>{const seq=['ArrowUp','ArrowUp','ArrowDown','ArrowDown','ArrowLeft','ArrowRight','ArrowLeft','ArrowRight','b','a'];let i=0;const k=e=>{i=e.key===seq[i]?i+1:0;if(i===seq.length){document.body.classList.toggle('maximum');alert('ROBIN MODE 69 UNLOCKED');i=0}};addEventListener('keydown',k);return()=>removeEventListener('keydown',k)},[]);
 useEffect(()=>{if(!abyssRef.current)return;const o=new IntersectionObserver(([e])=>{if(e.isIntersecting)setDepth(d=>Math.min(69,d+6))},{rootMargin:'900px'});o.observe(abyssRef.current);return()=>o.disconnect()},[]);
 const noise=()=>{setSound(true);const A=window.AudioContext||window.webkitAudioContext;if(!A)return;const c=new A();for(let i=0;i<9;i++){const o=c.createOscillator(),g=c.createGain();o.type=i%2?'square':'sawtooth';o.frequency.value=110+i*69;g.gain.setValueAtTime(.035,c.currentTime+i*.08);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+i*.08+.18);o.connect(g).connect(c.destination);o.start(c.currentTime+i*.08);o.stop(c.currentTime+i*.08+.2)}};
 const copy=()=>{navigator.clipboard?.writeText(CA);setCopied(true);setTimeout(()=>setCopied(false),1200)};
 return <>
 {!truth&&<div className="truth"><div className="truthbox"><div className="terminalbar">ROBINHOODTRUMPGAMESTOP69INU.EXE</div><h2>DO YOU ACCEPT THE GREEN CANDLE?</h2><p>This website may cause irreversible financial literacy loss.</p><div><button onClick={()=>setTruth(true)}>YES, I AM NORMAL</button><button onClick={()=>setTruth(true)} className="red">NO, I AM EARLY</button></div></div></div>}
 <button className="sound" onClick={noise} aria-label="Play website sounds">{sound?<Volume2/>:<VolumeX/>}</button>
 <div className="ticker"><span>*** POWER TO THE PLAYERS *** MIDNIGHT RELEASE AT SHERWOOD MALL *** GAMESTOP TRADE-IN VALUE: $6.90 OR 69,000 STORE POINTS *** PRINCE JOHN SHORT POSITION LIQUIDATED *** ROBIN NEON CANDLE DETECTED *** LITTLE JOHN IS HOLDING THE BAG *** </span></div>
 <img className="fixedgif leftgif foxfloat" src="/assets/community/fox-cash.jpeg" alt="Robin Hood fox archer fanning cash"/><img className="fixedgif rightgif mascotfloat" src="/assets/community/mascot.jpeg" alt="Robin Hood mascot with diamond and cash"/>
 {popups.includes(1)&&<div className="winpopup pop1"><div>GameStop Trade-In Wizard <button onClick={()=>setPopups(p=>p.filter(x=>x!==1))}>X</button></div><p>YOUR PORTFOLIO IS WORTH $3.47 STORE CREDIT.</p><button onClick={()=>alert('POWERUP REWARDS APPLIED. RECEIPT LENGTH: 69 FEET.')}>ACCEPT TRADE</button></div>}
 {popups.includes(2)&&<div className="winpopup pop2"><div>Congratulations!!! <button onClick={()=>setPopups(p=>p.filter(x=>x!==2))}>X</button></div><p>You are the 69th visitor.<br/>Claim FREE Robin Neon!</p><button onClick={()=>setPopups(p=>[...p,3])}>CLAIM PRIZE</button></div>}
 {popups.includes(3)&&<div className="winpopup pop3"><div>ERROR 420 <button onClick={()=>setPopups(p=>p.filter(x=>x!==3))}>X</button></div><p>Prize printer is out of ink.<br/>Buy RHTGS69 instead.</p></div>}
 <main>
  <div className="webmaster">WELCOME TO MY HOMEPAGE!!!!! <span>UNDER CONSTRUCTION SINCE 2009</span></div>
  <nav>{links.map(([t,h])=><a href={h} key={t}>{t}</a>)}<a href="#buy">BUY THE DIP</a></nav>
  <section id="welcome" className="hero">
   <div className="eyebrow">THE PEOPLE'S INFINITE LIQUIDITY EVENT</div>
   <h1><span>ROBINHOOD</span><span>TRUMP</span><span>GAMESTOP</span><span>69INU</span></h1>
   <p className="tickername">TICKER: $RHTGS69</p>
   <div className="gifrow"><img src="/assets/robin-neon-smiley.png"/><img src="/assets/robin-neon-smiley.png"/><span>POWER TO THE SHERWOOD PLAYERS</span><img src="/assets/robin-neon-smiley.png"/><img src="/assets/robin-neon-smiley.png"/></div>
   <div className="heroimg"><img src="/assets/rhtgs69-deepfried.png" alt="Malformed Donald Trump Robin Hood cutout riding with a distorted Shiba over a corrupted stock chart"/><div className="stamp">CERTIFIED<br/>69% REAL</div></div>
   <div className="contract"><b>THE SACRED NUMBERS:</b><code>{CA}</code><button onClick={copy}><Copy/>{copied?'COPIED. PROBABLY.':'COPY CONTRACT'}</button></div>
   <div className="market"><div><small>LIVE-ish PRICE</small><b>${price.toFixed(9)}</b></div><div><small>MARKET CAP</small><b>∞ + $69</b></div><div><small>HOLDERS</small><b>THE ENTIRE SHERWOOD FOREST</b></div></div>
   <div className="hoodterminal"><div className="hoodbar">ROBINHOOD LEGEND: SHERWOOD MARKET EDITION <span>[_][□][X]</span></div><div className="hoodbody"><aside><b>INVESTING</b><p>$69,420.69</p><small>+$6,969.69 TODAY</small><hr/><a>Stocks</a><a>Options</a><a>PowerUp Rewards</a><a>GameStop Preorders</a></aside><section><h3>RHTGS69</h3><div className="microchart">_╱╲_╱╲╱╲__╱╲╱╲╱╲╱╲╱╲╱╲╱╲╱</div><p>1D &nbsp; 1W &nbsp; MIDNIGHT RELEASE &nbsp; SHERWOOD</p></section><form onSubmit={e=>{e.preventDefault();alert('ORDER PRINTED ON A 69-FOOT GAMESTOP RECEIPT')}}><b>Buy RHTGS69</b><label>Dollars<input defaultValue="$69.00"/></label><label>Order type<select defaultValue="destiny"><option value="destiny">Market Destiny</option><option>Pre-Owned Limit</option><option>Nottingham Stop Loss</option></select></label><button>POWER TO THE ORDER</button></form></div></div>
  </section>

  <div className="browserwarn">[ POWERUP REWARDS WARNING ] This Sherwood brokerage experience requires a GameStop membership card, Netscape Navigator 4.7 and permission from the Sheriff of Nottingham. <u>PREORDER NOW</u></div>

  <section className="receipt"><div className="receiptlogo">GAME STOP? NEVER HEARD OF HER.</div><p>STORE #0069 — SHERWOOD MALL — NOTTINGHAM</p><hr/><table><tbody><tr><td>PRE-OWNED RHTGS69</td><td>$69.00</td></tr><tr><td>DISC PROTECTION PLAN</td><td>$6.90</td></tr><tr><td>LITTLE JOHN DLC</td><td>FREE</td></tr><tr><td>TRADE-IN: PRINCE JOHN CROWN</td><td>-$0.34</td></tr><tr><td>POWERUP REWARD POINTS</td><td>69,420</td></tr></tbody></table><hr/><b>POWER TO THE PLAYERS / ARROWS TO THE HEDGIES</b><div className="barcode">||| || ||||| | |||| || | ||||| ||</div><small>NO REFUNDS AFTER THE SHORT SQUEEZE. STORE CREDIT ONLY.</small></section>

  <section className="sherwood"><img src="/assets/community/fox-cash.jpeg" alt="Fox archer in green fanning cash"/><div><h2>THE SHERWOOD MARKET AUTHORITY</h2><p>Oo-de-lally: the fox is back from Nottingham with a quiver full of limit orders and a sack of used controllers. Little John runs risk management. Maid Marian handles investor relations. Friar Tuck validates the receipt printer. Prince John keeps shorting the float and losing the castle treasury.</p><p className="wanted">WANTED: THE SHERIFF OF NOTTINGHAM<br/>CRIME: CANCELING THE MIDNIGHT RELEASE<br/>REWARD: 69 POWERUP POINTS</p></div></section>

  <section id="chart" className="chart"><h2>ROADMAP TO THE MOON'S MOON</h2><div className="graph"><div className="line">╱╲__╱╲_╱╲╱╲___╱╲╱╲╱╲╱╲╱╲╱╲╱╲╱╲╱╲╱╲╱╲╱╲╱╲╱╲╱╲╱</div><strong>WE ARE HERE*</strong></div><p>*we are always here because the chart is a spiritual condition</p></section>

  <div className="junkstrip"><img src="/assets/community/mascot.jpeg"/><div><b>!!! MIDNIGHT RELEASE IN YOUR SHERWOOD AREA !!!</b><br/><span>CLICK HERE TO CHECK TRADE-IN VALUE</span><br/><button onClick={()=>alert('YOUR ENTIRE PORTFOLIO IS WORTH $6.90 STORE CREDIT')}>SCAN POWERUP CARD</button></div><img src="/assets/community/fox-cash.jpeg"/></div>

  <section id="buy" className="panel"><h2>HOW 2 ACQUIRE THE ARTIFACT</h2><ol><li>Download a wallet. Any wallet. A velcro wallet may not work.</li><li>Acquire ETH like a respectable digital medieval peasant.</li><li>Paste the sacred numbers into your swap cauldron.</li><li>Set slippage to “destiny” and smash the green button.</li><li>Tell your group chat you “like the fundamentals.”</li></ol><a className="cta" href="#welcome">I HAVE READ NOTHING <ArrowUpRight/></a></section>

  <section id="lore" className="lore"><h2>THE OFFICIAL UNAUTHORIZED SHERWOOD LORE</h2><div className="columns"><p>Before charts, before candles, before anyone's uncle discovered options trading, there was <em>The Hood</em>. The Hood was an extremely long username whispered into a GameStop receipt printer during a midnight release at exactly 6:9 PM.</p><p>From that sacred machine emerged RobinHoodTrumpGameStop69Inu: part statesman, part fox outlaw, part PowerUp Rewards member, part dog, and legally too many parts. He took basis points from Prince John and redistributed pre-owned controllers to every holder in Sherwood Forest.</p><p>The prophecy says that when sixty-nine Robin Neon candles align above Nottingham resistance, Little John will ring the opening bell, Maid Marian will approve the merger, and the Sheriff will be offered twelve cents of store credit for his castle.</p></div><blockquote>“EVERY PORTFOLIO DESERVES A SECOND LIFE AS A PRE-OWNED GAME.”<cite>— Receipt fragment found near Sherwood Mall</cite></blockquote></section>

  <section id="tokenomics" className="tokenomics"><h2>POWERUP TOKENOMICS</h2><div className="math"><div><b>69%</b><span>SHERWOOD LOOT</span></div><div><b>10%</b><span>USED GAME RECEIPTS</span></div><div><b>20%</b><span>LITTLE JOHN ARROW FUND</span></div><div><b>1%</b><span>PRINCE JOHN TAX</span></div></div><p>TOTAL SUPPLY: 69,000,000,000 • GAMESTOP STORE CREDIT: $6.90 • NOTTINGHAM TAX: REJECTED • POWER TO THE PLAYERS</p></section>

  <section id="memes" className="memes"><h2>CURSED FILES RECOVERED FROM THE FOREST</h2><p className="submitted">USER-SUBMITTED ARTIFACTS — DO NOT CLEAN, CROP, COLOR-CORRECT, OR ASK QUESTIONS</p><div className="grid">{communityMemes.map(([src,t],i)=><article key={t} className={`artifact artifact${i+1}`}><a href={src} target="_blank"><img src={src} alt={t}/></a><h3>{t}</h3><p>Right click → save as → re-upload at worse quality.</p></article>)}</div></section>
  <section className="aol"><h2>RHTGS69 LIVE COMMUNITY CHAT</h2><div className="chatroom"><div className="buddy"><b>BUDDY LIST</b><span>online: trumpdog69</span><span>online: HoodAdmin</span><span>away: DeepValueDad</span><span>idle: SEC_enjoyer</span></div><div className="messages">{['[HoodAdmin]: WELCOME NO FUD ALLOWED','[trumpdog69]: chart literally forming a robin hood hat','[DeepValueDad]: my financial advisor blocked me','[SEC_enjoyer]: hello fellow ordinary investors','[xX_420STONK_Xx]: WHO TOUCHED THE SELL BUTTON'][chat]}<br/><i>*** dialup_wizard has entered the room ***</i><input placeholder="say something irreversible..."/></div></div></section>
  <section className="guestbook"><h2>SIGN MY GUESTBOOK</h2><textarea defaultValue={'dear webmaster, this coin changed my life...'}></textarea><button onClick={()=>alert('GUESTBOOK FULL. TRY AGAIN IN 2009.')}>SUBMIT 2 INTERNET</button><div className="counter">YOU ARE VISITOR <b>000000069</b></div><p className="awards">[ COOL SITE AWARD ] [ NETSCAPE NOW! ] [ GEOCITIES SURVIVOR ] [ NO CSS VALIDATION ]</p></section>
  <footer><div className="gifrow"><img src="/assets/robin-neon-smiley.png"/><img src="/assets/robin-neon-smiley.png"/><img src="/assets/robin-neon-smiley.png"/></div><h2>ROBINHOODTRUMPGAMESTOP69INU</h2><p>A parody meme project. Not affiliated with Robinhood Markets, Donald Trump, GameStop, Disney, any fox, any dog, or any forest with securities jurisdiction.</p><p>© 2069 SHERWOOD GAMESTOP INTERNET DEPARTMENT</p><p>EMAIL THE WEBMASTER: powerupfox69@aol.example</p></footer>
  <section className="abyss"><div className="pointofreturn">END OF OFFICIAL WEBSITE<br/><small>EVERYTHING BELOW THIS LINE WAS RECOVERED FROM A GAMESTOP DISPLAY KIOSK</small></div>{Array.from({length:depth},(_,i)=>{const m=communityMemes[i%communityMemes.length];return <div className={`depth depth${i%9}`} key={i} style={{'--d':i}}><div className="corruptbar">SHERWOOD_STORE_{String(i+1).padStart(3,'0')}.HTML // POWERUP CARD EXPIRED // {i%3?'NOTTINGHAM CONNECTION UNSTABLE':'MIDNIGHT RELEASE CANCELED'}</div><h3>{['THE RECEIPT IS LOOKING BACK','ROBIN NEON LEAK DETECTED','PRINCE JOHN HAS BEEN MARGIN CALLED','69 POWERUP MEMBERS INSIDE THIS IMAGE','LITTLE JOHN KNOWS YOUR COST BASIS','THIS GAMESTOP HAS NO EXIT','SELL BUTTON TRADED FOR STORE CREDIT','SHERWOOD WEBMASTER IS TYPING...','WELCOME BACK PLAYER 000069'][i%9]}</h3><div className="corruptcontent"><img src={m[0]} alt="progressively corrupted Sherwood GameStop meme"/><div><p>{('POWER TO THE PLAYERS HOLD THE FOREST PREORDER THE SQUEEZE OOO-DE-LALLY ').repeat((i%4)+2)}</p><table><tbody><tr><td>POWERUP ACCOUNT</td><td>{(69*(i+1)).toLocaleString()} PTS</td></tr><tr><td>TRADE-IN STATUS</td><td>{i%2?'PRE-OWNED':'BUFFERING'}</td></tr><tr><td>SHERWOOD EQUITY</td><td>{99-i}%</td></tr></tbody></table><button onClick={()=>alert(`STORE ${i+1}: PRINCE JOHN DENIED YOUR REFUND`)}>ENTER GAMESTOP #{i+1}</button></div></div><div className="minimarquee">POWER TO THE PLAYERS RHTGS69 SHERWOOD FOREVER NOTTINGHAM LIQUIDATED RHTGS69</div></div>})}<div className="loadingabyss" ref={abyssRef}>{depth<69?'LOADING MORE GAMESTOP RECEIPT...':'YOU HAVE REACHED THE BACK OF SHERWOOD MALL.'}</div></section>
 </main></>}
createRoot(document.getElementById('root')).render(<App/>);
